<?php
/**
 * Concatenates the per-template CSS/JS source files into the two files
 * actually enqueued at runtime (assets/bwallet-frontend.css/.js), so the
 * source can live next to each template's .php file while still shipping
 * as a single file per type.
 *
 * Usage:
 *   php tools/build-assets.php          — (re)generate both files
 *   php tools/build-assets.php --check  — build in memory and compare
 *                                          against the checked-in files;
 *                                          exit code 1 on any mismatch
 *                                          (source changed, build forgotten)
 */

const BW_ASSETS_ROOT = __DIR__ . '/..';

/**
 * Template folders in a fixed, alphabetical order — the order the
 * sections appear in the built file, and the order build-assets.php
 * looks for an optional "<name>.css" / "<name>.js" inside each.
 */
function bw_assets_template_dirs(): array {
    $dirs = glob(BW_ASSETS_ROOT . '/templates/*', GLOB_ONLYDIR);
    sort($dirs, SORT_STRING);
    return $dirs;
}

/**
 * Reads a source file, strips its leading "/* path *\/" header comment
 * (each source file carries its own for standalone readability — the
 * built file gets a single section comment instead so it isn't doubled),
 * and returns the trimmed body.
 */
function bw_assets_read_body(string $path): string {
    $content = file_get_contents($path);
    if ($content === false) {
        throw new RuntimeException("Cannot read: {$path}");
    }
    $content = preg_replace('#^/\*.*?\*/\s*#s', '', $content, 1);
    return trim($content) . "\n";
}

function bw_assets_build_css(): string {
    $out = "/* assets/bwallet-frontend.css — generated by tools/build-assets.php, do not edit directly */\n\n";

    $out .= "/* ==== base ==== */\n";
    $out .= bw_assets_read_body(BW_ASSETS_ROOT . '/assets/base.css');

    foreach (bw_assets_template_dirs() as $dir) {
        $name = basename($dir);
        $file = $dir . '/' . $name . '.css';
        if (!is_file($file)) {
            continue;
        }
        $out .= "\n/* ==== {$name} ==== */\n";
        $out .= bw_assets_read_body($file);
    }

    return $out;
}

/** Indents every non-blank line by two spaces, leaving blank lines empty. */
function bw_assets_indent(string $text): string {
    $lines = explode("\n", rtrim($text));
    foreach ($lines as &$line) {
        if ($line !== '') {
            $line = '  ' . $line;
        }
    }
    return implode("\n", $lines);
}

function bw_assets_build_js(): string {
    $parts = [rtrim(bw_assets_read_body(BW_ASSETS_ROOT . '/assets/base.js'))];

    $course_list_js = BW_ASSETS_ROOT . '/templates/course_list/course_list.js';
    if (is_file($course_list_js)) {
        $parts[] = rtrim(bw_assets_read_body($course_list_js));
    }

    $body = bw_assets_indent(implode("\n\n", $parts));

    return "// assets/bwallet-frontend.js — generated by tools/build-assets.php, do not edit directly\n"
        . "(function () {\n"
        . $body . "\n"
        . "})();\n";
}

/**
 * Rebuilds both files in memory and compares them against what's already
 * on disk. Returns true only if both match exactly.
 */
function bw_assets_check(): bool {
    $ok = true;

    $targets = [
        BW_ASSETS_ROOT . '/assets/bwallet-frontend.css' => bw_assets_build_css(),
        BW_ASSETS_ROOT . '/assets/bwallet-frontend.js'  => bw_assets_build_js(),
    ];

    foreach ($targets as $path => $expected) {
        $actual = is_file($path) ? file_get_contents($path) : null;
        if ($actual !== $expected) {
            printf("FAIL: %s is out of date — run `php tools/build-assets.php` and commit the result\n", $path);
            $ok = false;
        } else {
            printf("PASS: %s is up to date\n", $path);
        }
    }

    return $ok;
}

// --- CLI entry point — only runs when this file is the directly
//     invoked script, not when it's require()'d as a library. ---
if (PHP_SAPI === 'cli' && isset($argv[0]) && realpath($argv[0]) === __FILE__) {
    if (in_array('--check', $argv, true)) {
        exit(bw_assets_check() ? 0 : 1);
    }

    file_put_contents(BW_ASSETS_ROOT . '/assets/bwallet-frontend.css', bw_assets_build_css());
    file_put_contents(BW_ASSETS_ROOT . '/assets/bwallet-frontend.js', bw_assets_build_js());

    echo "Built assets/bwallet-frontend.css and assets/bwallet-frontend.js\n";
}
