<?php
/**
 * Generates languages/bw-credits-booking.pot from three sources:
 *
 *   1. includes/text.php's BW_Text::catalogue() defaults — passed to
 *      __() as a variable at runtime, invisible to any static scanner,
 *      so we iterate the catalogue array directly instead.
 *   2. includes/text.php's BW_Text::GROUPS — same reasoning (PHP forbids
 *      function calls in const initializers, so these are also plain
 *      array values, not literal __() call arguments anywhere).
 *   3. tools/scan-source-strings.php's token-based scan of the plugin's
 *      admin-facing PHP files, which finds genuine literal-string
 *      __()/esc_html__()/etc. calls using the bw-credits-booking domain.
 *
 * All three merge into one dedup pass (by text, case-sensitive) so a
 * string appearing in more than one source/place gets a single .pot
 * entry with every source noted in its #: comment lines.
 *
 * Usage:  php tools/make-pot.php
 */

if (PHP_SAPI !== 'cli') exit(1);

define('ABSPATH', true);

// Minimal stubs — we only need catalogue()
if (!function_exists('add_action'))            { function add_action(...$a) {} }
if (!function_exists('__'))                    { function __($t, $d = null) { return $t; } }
if (!function_exists('has_action'))            { function has_action(...$a) { return false; } }
if (!function_exists('has_filter'))            { function has_filter(...$a) { return false; } }
if (!function_exists('get_option'))            { function get_option($k, $d = false) { return $d; } }
if (!function_exists('plugin_basename'))       { function plugin_basename($f) { return $f; } }
if (!function_exists('load_plugin_textdomain')){ function load_plugin_textdomain(...$a) {} }
if (!defined('BW_CREDITS_BOOKING_FILE'))       { define('BW_CREDITS_BOOKING_FILE', __FILE__); }

require __DIR__ . '/po-format.php';
require __DIR__ . '/scan-source-strings.php';
require __DIR__ . '/../includes/text.php';

$out  = "# BW Credits + Bookings\n";
$out .= "# Generated by tools/make-pot.php — do not edit by hand.\n";
$out .= "msgid \"\"\nmsgstr \"\"\n";
$out .= "\"Project-Id-Version: BW Credits + Bookings\\n\"\n";
$out .= "\"MIME-Version: 1.0\\n\"\n";
$out .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n";
$out .= "\"Content-Transfer-Encoding: 8bit\\n\"\n";
$out .= "\"X-Domain: bw-credits-booking\\n\"\n\n";

$seen = []; // text => true, shared dedup across all three sources
$total_candidates = 0;

$write_entry = function (string $text, array $comment_lines) use (&$out, &$seen) {
    if (isset($seen[$text])) {
        // Same text already emitted from an earlier source/location —
        // one .pot entry only, otherwise msgfmt rejects duplicate msgids
        return;
    }
    $seen[$text] = true;

    $escaped = bw_po_escape($text);
    foreach ($comment_lines as $line) {
        $out .= "{$line}\n";
    }
    $out .= "msgid \"{$escaped}\"\n";
    $out .= "msgstr \"\"\n\n";
};

// --- 1. Catalogue defaults ---
$catalogue = BW_Text::catalogue();
foreach ($catalogue as $key => [$default, $description, $group]) {
    $total_candidates++;
    $write_entry($default, ["#. {$description}", "#: catalogue:{$key}"]);
}

// --- 2. GROUPS headings ---
foreach (BW_Text::GROUPS as $group_key => $heading) {
    $total_candidates++;
    $write_entry($heading, ["#. Text-Katalog group heading", "#: catalogue:GROUPS.{$group_key}"]);
}

// --- 3. Scanned literal __()-style calls across the admin-facing PHP files ---
$scanned = bw_scan_source_strings(bw_scan_default_files());
foreach ($scanned as $text => $locations) {
    $total_candidates++;
    $comment_lines = array_map(fn ($loc) => "#: {$loc}", $locations);
    $write_entry($text, $comment_lines);
}

file_put_contents(__DIR__ . '/../languages/bw-credits-booking.pot', $out);
printf("%d entries written (%d candidates, %d duplicates merged)\n",
    count($seen), $total_candidates, $total_candidates - count($seen));
